In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('blinkit customer behaviour unclean dataset.csv')

to upload file in jupyter notebook

In [3]:
df.columns.values

<StringArray>
[     'customer_id',    'customer_name',              'age',
           'gender',             'city',     'subscription',
 'discount_applied',   'item_purchased',         'category',
  'purchase_amount',   'payment_method',    'purchase_date']
Length: 12, dtype: str

To see columns values

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       510 non-null    int64
 1   customer_name     510 non-null    str
 2   age               510 non-null    int64
 3   gender            510 non-null    str
 4   city              510 non-null    str
 5   subscription      510 non-null    str
 6   discount_applied  360 non-null    str
 7   item_purchased    494 non-null    str
 8   category          510 non-null    str
 9   purchase_amount   510 non-null    int64
 10  payment_method    510 non-null    str
 11  purchase_date     510 non-null    str
dtypes: int64(3), str(9)
memory usage: 47.9 KB

to see all info of the data

In [5]:
df.isnull().sum()

customer_id           0
customer_name         0
age                   0
gender                0
city                  0
subscription          0
discount_applied    150
item_purchased       16
category              0
purchase_amount       0
payment_method        0
purchase_date         0
dtype: int64

to see the all null values has been there or not

In [6]:
df["discount_applied"] = df["discount_applied"].fillna("No")
df["item_purchased"] = df["item_purchased"].fillna("Unknown")

to remove all null values

In [7]:
df.isnull().sum()

customer_id         0
customer_name       0
age                 0
gender              0
city                0
subscription        0
discount_applied    0
item_purchased      0
category            0
purchase_amount     0
payment_method      0
purchase_date       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(10)

to find all duplicate raw

In [9]:
df = df.drop_duplicates()

to remove all duplicate raws

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dtypes

customer_id         int64
customer_name         str
age                 int64
gender                str
city                  str
subscription          str
discount_applied      str
item_purchased        str
category              str
purchase_amount     int64
payment_method        str
purchase_date         str
dtype: object

to see data type

In [25]:
df.columns.values

<StringArray>
[     'customer_id',    'customer_name',              'age',
           'gender',             'city',     'subscription',
 'discount_applied',   'item_purchased',         'category',
  'purchase_amount',   'payment_method',    'purchase_date']
Length: 12, dtype: str

In [26]:
text_columns = ["customer_name", "gender", "city", "subscription",
                "discount_applied", "item_purchased", "category",
                "payment_method"]

for columns in text_columns:
    df[columns] = df[columns].str.strip()

to remove extra spaces and string value in text

In [27]:
df.head()

,customer_id,customer_name,age,gender,city,subscription,discount_applied,item_purchased,category,purchase_amount,payment_method,purchase_date
0,1001,Sara,50,Male,Gurugram,No,Yes,Face Wash,Beauty,2936,Net Banking,2025-07-19
1,1002,Vikas,24,Female,Delhi,No,No,Keyboard,Electronics,63049,Net Banking,2025-03-23
2,1003,Rohan,50,Female,Delhi,Yes,No,Watch,Fashion,17778,Net Banking,2025-03-19
3,1004,Ali,42,Male,Noida,Yes,No,Tea,Groceries,16859,Card,2025-10-30
4,1005,Karan,56,Male,Meerut,Yes,Yes,Keyboard,Electronics,55425,UPI,2025-12-04

In [28]:
df["city"] = df["city"].str.title()

In [30]:
df.columns.values

<StringArray>
[     'customer_id',    'customer_name',              'age',
           'gender',             'city',     'subscription',
 'discount_applied',   'item_purchased',         'category',
  'purchase_amount',   'payment_method',    'purchase_date']
Length: 12, dtype: str

In [37]:
df["gender"] = df["gender"].str.title()

In [38]:
df["discount_applied"] = df["discount_applied"].str.title()

In [39]:
df["payment_method"] = df["payment_method"].str.title()

to standardize the columns

In [45]:
df[df["purchase_amount"] < 0]

,customer_id,customer_name,age,gender,city,subscription,discount_applied,item_purchased,category,purchase_amount,payment_method,purchase_date
14,1015,Neha,24,Female,Meerut,Yes,Yes,Tea,Groceries,-33378,Card,2025-04-26
21,1022,Priya,47,Female,Gurugram,No,No,Rice,Groceries,-64021,Cash,2025-04-24
22,1023,Aman,20,Male,Lucknow,No,No,Laptop,Electronics,-20607,Net Banking,2025-01-28
40,1041,Farhan,53,Male,Gurugram,Yes,No,Laptop,Electronics,-56934,Card,2025-06-08
52,1053,Karan,33,Female,Noida,Yes,No,Football,Sports,-16017,Card,2025-09-15
87,1088,Farhan,50,Female,Lucknow,Yes,No,Cricket Bat,Sports,-51915,Net Banking,2025-08-17
142,1143,Rohan,33,Male,Lucknow,Yes,No,Shoes,Fashion,-24109,Card,2025-04-12
145,1146,Farhan,48,Female,Gurugram,No,Yes,Face Wash,Beauty,-48341,Card,2025-02-11
169,1170,Zoya,27,Male,Gurugram,Yes,No,Football,Sports,-12024,Card,2025-04-20
210,1211,Neha,21,Male,Meerut,Yes,Yes,Milk,Groceries,-27332,Net Banking,2025-01-02
222,1223,Karan,52,Female,Noida,No,No,Mouse,Electronics,-23473,Net Banking,2025-02-08
257,1258,Vikas,27,Male,Delhi,No,Yes,Milk,Groceries,-35456,Cash,2025-11-18
265,1266,Neha,54,Male,Noida,No,No,Milk,Groceries,-53922,Cash,2025-01-18
286,1287,Neha,21,Female,Lucknow,No,No,Mobile,Electronics,-55120,Card,2025-03-08
290,1291,Karan,24,Female,Delhi,Yes,Yes,Shampoo,Beauty,-64400,Cash,2025-07-19
301,1302,Aman,47,Female,Delhi,No,Yes,Rice,Groceries,-28419,Cash,2025-07-13
335,1336,Neha,38,Male,Noida,Yes,No,T-Shirt,Fashion,-44685,Cash,2025-04-26
347,1348,Aman,23,Male,Noida,No,Yes,Cricket Bat,Sports,-21517,Net Banking,2025-01-09
374,1375,Sara,25,Male,Lucknow,No,No,Rice,Groceries,-4897,Upi,2025-07-28
375,1376,Karan,51,Female,Noida,No,No,Football,Sports,-56431,Cash,2025-02-28
420,1421,Sara,24,Male,Delhi,No,No,Rice,Groceries,-38576,Card,2025-10-17
480,1481,Neha,38,Female,Lucknow,Yes,Yes,Mouse,Electronics,-40300,Card,2025-05-14

In [46]:
df["city"].unique()

<StringArray>
['Gurugram', 'Delhi', 'Noida', 'Meerut', 'Lucknow']
Length: 5, dtype: str

In [47]:
df["gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [48]:
df["payment_method"].unique()

<StringArray>
['Net Banking', 'Card', 'Upi', 'Cash']
Length: 4, dtype: str

In [49]:
df.columns.values

<StringArray>
[     'customer_id',    'customer_name',              'age',
           'gender',             'city',     'subscription',
 'discount_applied',   'item_purchased',         'category',
  'purchase_amount',   'payment_method',    'purchase_date']
Length: 12, dtype: str

In [50]:
df["subscription"].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [51]:
df["discount_applied"].unique()

<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [52]:
df["category"].unique()

<StringArray>
['Beauty', 'Electronics', 'Fashion', 'Groceries', 'Sports']
Length: 5, dtype: str

In [54]:
(df["purchase_amount"] <0).sum()

np.int64(22)

In [56]:
((df["purchase_amount"] < 0).sum() / len(df)) * 100

np.float64(4.3999999999999995)

In [57]:
df["purchase_amount"] = df["purchase_amount"].abs()

In [60]:
(df["purchase_amount"] <0).sum()

np.int64(0)

In [61]:
df.describe()

       customer_id        age  purchase_amount
count   500.000000  500.00000       500.000000
mean   1250.500000   38.32000     36246.914000
std     144.481833   12.65836     20744.026136
min    1001.000000   18.00000       222.000000
25%    1125.750000   27.00000     19356.500000
50%    1250.500000   38.00000     34855.000000
75%    1375.250000   50.00000     55156.000000
max    1500.000000   60.00000     69834.000000

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       500 non-null    int64
 1   customer_name     500 non-null    str
 2   age               500 non-null    int64
 3   gender            500 non-null    str
 4   city              500 non-null    str
 5   subscription      500 non-null    str
 6   discount_applied  500 non-null    str
 7   item_purchased    500 non-null    str
 8   category          500 non-null    str
 9   purchase_amount   500 non-null    int64
 10  payment_method    500 non-null    str
 11  purchase_date     500 non-null    str
dtypes: int64(3), str(9)
memory usage: 47.0 KB

In [64]:
df["purchase_date"] = pd.to_datetime(df["purchase_date"])

to convert text to date format in purchase_date

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       500 non-null    int64
 1   customer_name     500 non-null    str
 2   age               500 non-null    int64
 3   gender            500 non-null    str
 4   city              500 non-null    str
 5   subscription      500 non-null    str
 6   discount_applied  500 non-null    str
 7   item_purchased    500 non-null    str
 8   category          500 non-null    str
 9   purchase_amount   500 non-null    int64
 10  payment_method    500 non-null    str
 11  purchase_date     500 non-null    datetime64[us]
dtypes: datetime64[us](1), int64(3), str(8)
memory usage: 47.0 KB

In [72]:
df.columns.values

<StringArray>
[     'customer_id',    'customer_name',              'age',
           'gender',             'city',     'subscription',
 'discount_applied',   'item_purchased',         'category',
  'purchase_amount',   'payment_method',    'purchase_date']
Length: 12, dtype: str

In [77]:
df["age_group"] = pd.cut(
    df["age"],
    bins = [17,25,35,45,60],
    labels=["18-25","26-35","36-45","46-60"]
)

to create age group in dataframe

In [81]:
df['purchase_month'] = df["purchase_date"].dt.month_name()

to create a month columns in dataframe

In [83]:
df["purchase_day"] = df["purchase_date"].dt.day_name()

to create a day column in dataframe

In [85]:
df["purchase_year"] = df["purchase_date"].dt.year

to create year column in dataframe

In [86]:
df.columns

Index(['customer_id', 'customer_name', 'age', 'gender', 'city', 'subscription',
       'discount_applied', 'item_purchased', 'category', 'purchase_amount',
       'payment_method', 'purchase_date', 'age_group', 'purchase_month',
       'purchase_day', 'purchase_year'],
      dtype='str')

In [89]:
df["discount_flag"] = df["discount_applied"].map({
    "Yes":1,
    "No":0
})

to create a discount_flag column in dataframe

In [90]:
df.head()

,customer_id,customer_name,age,gender,city,subscription,discount_applied,item_purchased,category,purchase_amount,payment_method,purchase_date,age_group,purchase_month,purchase_day,purchase_year,discount_flag
0,1001,Sara,50,Male,Gurugram,No,Yes,Face Wash,Beauty,2936,Net Banking,2025-07-19,46-60,July,Saturday,2025,1
1,1002,Vikas,24,Female,Delhi,No,No,Keyboard,Electronics,63049,Net Banking,2025-03-23,18-25,March,Sunday,2025,0
2,1003,Rohan,50,Female,Delhi,Yes,No,Watch,Fashion,17778,Net Banking,2025-03-19,46-60,March,Wednesday,2025,0
3,1004,Ali,42,Male,Noida,Yes,No,Tea,Groceries,16859,Card,2025-10-30,36-45,October,Thursday,2025,0
4,1005,Karan,56,Male,Meerut,Yes,Yes,Keyboard,Electronics,55425,Upi,2025-12-04,46-60,December,Thursday,2025,1

In [91]:
df["revenue_segment"] = pd.cut(
    df["purchase_amount"],
    bins = [0,10000,30000,50000,70000],
    labels = ["low","medium","high","premium"]
)

In [92]:
df.columns

Index(['customer_id', 'customer_name', 'age', 'gender', 'city', 'subscription',
       'discount_applied', 'item_purchased', 'category', 'purchase_amount',
       'payment_method', 'purchase_date', 'age_group', 'purchase_month',
       'purchase_day', 'purchase_year', 'discount_flag', 'revenue_segment'],
      dtype='str')

In [94]:
df.to_csv("blinkit_clean_customer_behaviour.csv", index=False)